services:
  - type: web
    name: online-poker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 100 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
